[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
    "motor>=3.6.0",
    "beanie>=2.0.1",
]
